In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('test_lab.csv')

In [3]:
df

id                                             smiles  efficiency  \
0    0          COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21         NaN   
1    1          COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21         NaN   
2    2          COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21         NaN   
3    3          COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21         NaN   
4    4          COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21         NaN   
5    5          COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21         NaN   
6    6                      O=C1CCCC2C3CCCN4CCCC(CN12)C34         NaN   
7    7                      O=C1CCCC2C3CCCN4CCCC(CN12)C34         NaN   
8    8                      O=C1CCCC2C3CCCN4CCCC(CN12)C34         NaN   
9    9                      O=C1CCCC2C3CCCN4CCCC(CN12)C34         NaN   
10  10                      O=C1CCCC2C3CCCN4CCCC(CN12)C34         NaN   
11  11                      O=C1CCCC2C3CCCN4CCCC(CN12)C34         NaN   
12  12                           C=C/C(O)=N/C/N=C(\\O)C=C         NaN   
13  13                           C=C/C(O)=N/C/N=C(\\O)C=C         NaN   
14  14                           C=C/C(O)=N/C/N=C(\\O)C=C         NaN   
15  15                           C=C/C(O)=N/C/N=C(\\O)C=C         NaN   
16  16                           C=C/C(O)=N/C/N=C(\\O)C=C         NaN   
17  17                           C=C/C(O)=N/C/N=C(\\O)C=C         NaN   
18  18  OC[C@H]1OC2OC3[C@@H](CO)OC(OC4[C@@H](CO)OC(OC5...         NaN   
19  19  OC[C@H]1OC2OC3[C@@H](CO)OC(OC4[C@@H](CO)OC(OC5...         NaN   
20  20  OC[C@H]1OC2OC3[C@@H](CO)OC(OC4[C@@H](CO)OC(OC5...         NaN   
21  21  OC[C@H]1OC2OC3[C@@H](CO)OC(OC4[C@@H](CO)OC(OC5...         NaN   
22  22  OC[C@H]1OC2OC3[C@@H](CO)OC(OC4[C@@H](CO)OC(OC5...         NaN   
23  23  OC[C@H]1OC2OC3[C@@H](CO)OC(OC4[C@@H](CO)OC(OC5...         NaN   
24  24                     CN(C)NC(=O)NCCCCCCNC(=O)NN(C)C         NaN   
25  25                     CN(C)NC(=O)NCCCCCCNC(=O)NN(C)C         NaN   
26  26                     CN(C)NC(=O)NCCCCCCNC(=O)NN(C)C         NaN   
27  27                     CN(C)NC(=O)NCCCCCCNC(=O)NN(C)C         NaN   
28  28                     CN(C)NC(=O)NCCCCCCNC(=O)NN(C)C         NaN   
29  29                     CN(C)NC(=O)NCCCCCCNC(=O)NN(C)C         NaN   

    concentration  
0           0.001  
1           0.010  
2           0.050  
3           0.100  
4           0.500  
5           1.000  
6           0.001  
7           0.010  
8           0.050  
9           0.100  
10          0.500  
11          1.000  
12          0.001  
13          0.010  
14          0.050  
15          0.100  
16          0.500  
17          1.000  
18          0.001  
19          0.010  
20          0.050  
21          0.100  
22          0.500  
23          1.000  
24          0.001  
25          0.010  
26          0.050  
27          0.100  
28          0.500  
29          1.000

In [4]:
# 获得id号
id_list=np.array(df['id']) #  id号
id_list 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64)

In [5]:
#获得gap
gap=np.array(df['HOMO-LUMO gap'])
gap

KeyError: 'HOMO-LUMO gap'

In [34]:
# 获得efficiency
efficiency=np.array(df['efficiency'])
efficiency

array([0.9103, 0.75  , 0.7703, ..., 0.91  , 0.89  , 0.8   ])

In [8]:
# 获得HOMO
HOMO=np.array(df['EHOMO'])
HOMO

array([-6.919879, -7.14976 , -5.995903, -5.607875, -5.542968, -4.807087,
       -6.454891, -5.939595, -5.767365, -5.950435, -5.075112, -5.597887,
       -6.266132, -5.719688, -5.572369, -5.700917, -5.595787, -6.345043,
       -5.875056, -6.617426, -5.525293, -5.738286, -5.418544, -5.166709,
       -5.654169, -5.721373, -6.297733, -4.497541, -4.637713, -4.999483,
       -6.099424, -4.903692, -5.429518, -5.39439 , -5.784668, -5.519163,
       -5.700577, -5.633625, -5.579318, -5.274495, -6.314305, -5.842595,
       -6.403489, -5.565206, -6.499684, -6.255675, -6.280779, -5.81889 ,
       -6.36457 , -6.175853, -6.238392, -6.143381, -5.113207, -5.795556,
       -5.97452 , -5.511121, -5.517435, -5.481751, -6.216111, -5.170612,
       -6.0014  , -5.50713 , -5.705174, -5.202205, -5.196825, -6.438904,
       -6.382222, -5.856862, -5.353313, -6.601108, -6.113366, -3.577083,
       -5.187979, -6.15213 , -6.352787, -5.127704, -6.090353, -5.928062,
       -6.005811, -6.394283, -5.832662, -6.326289, 

In [9]:
# 获得LUMO
LUMO=np.array(df['ELUMO'])
LUMO

array([-0.560024, -1.107006, -1.983971, -1.515288, -2.167025,  0.222618,
       -1.663445, -1.656223, -1.523876, -2.042804, -1.457757, -1.401274,
       -1.82694 , -1.447395, -1.305018, -1.584424, -1.350137, -1.093521,
       -0.623793, -0.626218, -1.421165, -1.92322 , -1.54231 , -1.574802,
       -0.335716, -0.512785, -0.965123,  0.97341 , -1.969122, -1.201511,
        0.564709, -0.754424, -1.815006, -1.664211, -1.699601, -1.538134,
       -0.946629, -1.669376, -1.264301,  0.014929,  0.475176,  0.939347,
       -1.838161, -0.359912, -2.056945, -1.05971 , -1.048768, -0.537748,
       -1.066859, -0.9132  , -0.89563 , -0.741115, -0.091726, -0.188148,
       -0.311481, -0.987326, -1.839908, -1.799071, -2.672539, -0.802136,
       -2.819859, -1.012187, -1.19448 , -1.036494, -0.768237, -0.733965,
       -0.506698, -0.397163, -1.608351, -2.613373, -2.835702,  0.486955,
        0.287173, -1.264063, -3.93095 , -0.470494, -2.369436, -1.288786,
       -1.351061, -2.776774, -1.220138,  0.192716, 

In [10]:
# 获得硬度
Hardness=np.array(df['Hardness'])
Hardness

array([ 9.8118,  9.6361,  7.0857,  6.3679,  7.3355,  8.9631,  8.5499,
        7.4088,  7.5243,  6.7932,  6.5817,  7.4092,  8.3966,  8.1159,
        7.9405,  7.6849,  7.7558,  8.123 ,  8.3883,  9.0519,  7.3491,
        7.0067,  6.9799,  6.7241,  8.6333,  7.8608,  8.0798,  9.5098,
        5.9877,  6.4342,  9.3445,  7.3577,  6.0066,  6.9319,  7.2492,
        7.0776,  7.4526,  6.5863,  7.3857,  8.9409, 11.5087, 11.4772,
        8.0963,  8.9469,  8.0673,  8.6549,  8.7677,  8.9229,  8.9388,
        9.1207,  9.0507,  9.1922,  8.9344,  9.376 ,  9.5017,  7.9852,
        6.038 ,  5.8009,  6.8416,  7.4576,  6.6832,  7.6519,  7.7416,
        6.7291,  6.9771,  8.8898,  8.8001,  8.5448,  6.4259,  6.6127,
        6.2008,  7.401 ,  8.8842,  8.2925,  5.575 ,  7.9626,  6.5398,
        7.6553,  7.7666,  6.9092,  7.6241, 10.7115, 10.9036,  7.1271,
        6.7619,  7.287 ,  7.279 ,  7.3351,  7.4066,  8.3137,  8.7829,
        6.604 ,  8.1031,  8.1652,  7.1157, 10.3696,  7.1634,  7.7725,
        7.2782,  6.5

In [11]:
# 获得软度
Softness=np.array(df['Softness'])
Softness

array([0.1019, 0.1038, 0.1411, 0.157 , 0.1363, 0.1116, 0.117 , 0.135 ,
       0.1329, 0.1472, 0.1519, 0.135 , 0.1191, 0.1232, 0.1259, 0.1301,
       0.1289, 0.1231, 0.1192, 0.1105, 0.1361, 0.1427, 0.1433, 0.1487,
       0.1158, 0.1272, 0.1238, 0.1052, 0.167 , 0.1554, 0.107 , 0.1359,
       0.1665, 0.1443, 0.1379, 0.1413, 0.1342, 0.1518, 0.1354, 0.1118,
       0.0869, 0.0871, 0.1235, 0.1118, 0.124 , 0.1155, 0.1141, 0.1121,
       0.1119, 0.1096, 0.1105, 0.1088, 0.1119, 0.1067, 0.1052, 0.1252,
       0.1656, 0.1724, 0.1462, 0.1341, 0.1496, 0.1307, 0.1292, 0.1486,
       0.1433, 0.1125, 0.1136, 0.117 , 0.1556, 0.1512, 0.1613, 0.1351,
       0.1126, 0.1206, 0.1794, 0.1256, 0.1529, 0.1306, 0.1288, 0.1447,
       0.1312, 0.0934, 0.0917, 0.1403, 0.1479, 0.1372, 0.1374, 0.1363,
       0.135 , 0.1203, 0.1139, 0.1514, 0.1234, 0.1225, 0.1405, 0.0964,
       0.1396, 0.1287, 0.1374, 0.1537, 0.1303, 0.1297, 0.1394, 0.0862,
       0.0894, 0.1263, 0.1301, 0.1227, 0.1271, 0.1042, 0.133 , 0.1264,
      

In [5]:
# 获得smiles列表
smiles_list=np.array(df['smiles'])
smiles_list

array(['COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21',
       'COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21',
       'COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21',
       'COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21',
       'COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21',
       'COC(=O)c1ccccc1C1c2ccc(N)cc2Oc2cc(N)ccc21',
       'O=C1CCCC2C3CCCN4CCCC(CN12)C34', 'O=C1CCCC2C3CCCN4CCCC(CN12)C34',
       'O=C1CCCC2C3CCCN4CCCC(CN12)C34', 'O=C1CCCC2C3CCCN4CCCC(CN12)C34',
       'O=C1CCCC2C3CCCN4CCCC(CN12)C34', 'O=C1CCCC2C3CCCN4CCCC(CN12)C34',
       'C=C/C(O)=N/C/N=C(\\\\O)C=C', 'C=C/C(O)=N/C/N=C(\\\\O)C=C',
       'C=C/C(O)=N/C/N=C(\\\\O)C=C', 'C=C/C(O)=N/C/N=C(\\\\O)C=C',
       'C=C/C(O)=N/C/N=C(\\\\O)C=C', 'C=C/C(O)=N/C/N=C(\\\\O)C=C',
       'OC[C@H]1OC2OC3[C@@H](CO)OC(OC4[C@@H](CO)OC(OC5[C@@H](CO)O[C@H](OC6[C@@H](CO)OC(O[C@@H]7[C@@H](CO)OC(OC8[C@@H](CO)O[C@H](OC1[C@H](O)C2O)[C@H](O)[C@H]8O)C(O)[C@H]7O)C(O)[C@H]6O)[C@H](O)[C@H]5O)[C@H](O)[C@H]4O)[C@H](O)[C@H]3O',
       'OC[C@H]1OC2OC3[C@@H](CO)OC(

In [6]:
from rdkit import Chem

In [7]:
# 获得每个分子包含的原子数
N=[]  # 每个分子包含的原子个数
for smiles in smiles_list:
    mol = Chem.MolFromSmiles(smiles)
    atom_num = mol.GetNumAtoms()
    N.append(atom_num)
N=np.array(N)
print(N)
N.shape

[26 26 26 26 26 26 18 18 18 18 18 18 11 11 11 11 11 11 77 77 77 77 77 77
 20 20 20 20 20 20]


(30,)

In [8]:
# 下一步获得R
# 遍历mol文件夹中的文件
path = 'E:/马金博/缓蚀剂研究/三维数据集制作/test3/'
file_txt = os.listdir(path)
file_txt.sort(key=lambda x:int(x[:-4]))  #解决os.listdir读取数据的乱序问题
# print(file_txt)
contents=[]
for n,name in zip(N,file_txt):
    file_path=os.path.join(path, name)
#     print(file_path)
    f = open(file_path) # 依次读取文件
#     print(f)
    content=f.read().split('\n')
#     print(name)
    for i in range(4,n+4):
#         print(i)
        a=content[i].split()
        contents.append(a[0:4])
       
    
print(contents)        
    
# lines = f.read() 
# lines
# a=lines.split('\n')
# a[5].split()
# # for line in lines:
# #     print(line)


[['4.8925', '0.0123', '1.2766', 'C'], ['4.0909', '0.2001', '0.1100', 'O'], ['3.0649', '-0.6800', '0.0051', 'C'], ['2.7816', '-1.5698', '0.7878', 'O'], ['2.2988', '-0.3720', '-1.2221', 'C'], ['3.0079', '-0.3254', '-2.4348', 'C'], ['2.3403', '-0.0775', '-3.6323', 'C'], ['0.9638', '0.1214', '-3.6266', 'C'], ['0.2539', '0.0777', '-2.4248', 'C'], ['0.9044', '-0.1674', '-1.1964', 'C'], ['0.0888', '-0.1659', '0.1014', 'C'], ['-0.5334', '1.1932', '0.3679', 'C'], ['0.2655', '2.3168', '0.6288', 'C'], ['-0.3204', '3.5674', '0.8451', 'C'], ['-1.7085', '3.7148', '0.8486', 'C'], ['-2.2821', '4.9883', '0.9445', 'N'], ['-2.4983', '2.6070', '0.5355', 'C'], ['-1.9193', '1.3511', '0.3254', 'C'], ['-2.7909', '0.3209', '0.0666', 'O'], ['-2.3067', '-0.9649', '0.0950', 'C'], ['-3.2666', '-1.9824', '0.0797', 'C'], ['-2.8870', '-3.3238', '0.1542', 'C'], ['-3.8432', '-4.3385', '0.0241', 'N'], ['-1.5262', '-3.6340', '0.1400', 'C'], ['-0.5620', '-2.6219', '0.1480', 'C'], ['-0.9460', '-1.2732', '0.1249', 'C'], ['4

In [9]:
# 获得原子
atoms=[]
for content in contents:
    atom=content[3]
    atoms.append(atom)
print(atoms)

['C', 'O', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'O', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'O', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'O', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'O', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'O', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C',

In [10]:
# 获得原子对应得坐标，并转为数字
R=[]
for content in contents:
    r_float=[]
    for i in content[:3]:
        r_float.append(float(i))
    R.append(r_float)
R=np.array(R)
R

array([[ 4.8925e+00,  1.2300e-02,  1.2766e+00],
       [ 4.0909e+00,  2.0010e-01,  1.1000e-01],
       [ 3.0649e+00, -6.8000e-01,  5.1000e-03],
       ...,
       [ 6.7090e+00, -6.4780e-01, -6.0680e-01],
       [ 7.4080e+00,  5.9550e-01, -9.3640e-01],
       [ 6.9211e+00, -1.0237e+00,  7.9160e-01]])

In [11]:
# 计算对应原子的核电荷数
Z = []
for atom in atoms:
    if atom=='N':
        Z.append(7)
    elif atom=='Br':
        Z.append(35)
    elif atom=='C':
        Z.append(6)
    elif atom=='O':
        Z.append(8)
    elif atom=='K':
        Z.append(19)
    elif atom=='S':
        Z.append(16)
    elif atom=='Cl':
        Z.append(17)
    elif atom=='F':
        Z.append(9)
    elif atom=='P':
        Z.append(15)
    elif atom=='H':
        Z.append(1)
    elif atom=='I':
        Z.append(53)
    elif atom=='Na':
        Z.append(11)
Z=np.array(Z)
print(Z)

[6 8 6 8 6 6 6 6 6 6 6 6 6 6 6 7 6 6 8 6 6 6 7 6 6 6 6 8 6 8 6 6 6 6 6 6 6
 6 6 6 6 7 6 6 8 6 6 6 7 6 6 6 6 8 6 8 6 6 6 6 6 6 6 6 6 6 6 7 6 6 8 6 6 6
 7 6 6 6 6 8 6 8 6 6 6 6 6 6 6 6 6 6 6 7 6 6 8 6 6 6 7 6 6 6 6 8 6 8 6 6 6
 6 6 6 6 6 6 6 6 7 6 6 8 6 6 6 7 6 6 6 6 8 6 8 6 6 6 6 6 6 6 6 6 6 6 7 6 6
 8 6 6 6 7 6 6 6 8 6 6 6 6 6 6 6 6 6 7 6 6 6 6 6 7 6 8 6 6 6 6 6 6 6 6 6 7
 6 6 6 6 6 7 6 8 6 6 6 6 6 6 6 6 6 7 6 6 6 6 6 7 6 8 6 6 6 6 6 6 6 6 6 7 6
 6 6 6 6 7 6 8 6 6 6 6 6 6 6 6 6 7 6 6 6 6 6 7 6 8 6 6 6 6 6 6 6 6 6 7 6 6
 6 6 6 7 6 6 6 6 8 7 6 7 6 8 6 6 6 6 6 8 7 6 7 6 8 6 6 6 6 6 8 7 6 7 6 8 6
 6 6 6 6 8 7 6 7 6 8 6 6 6 6 6 8 7 6 7 6 8 6 6 6 6 6 8 7 6 7 6 8 6 6 8 6 6
 8 6 8 6 6 6 8 8 6 8 6 6 6 8 8 6 8 6 6 6 8 8 6 8 6 6 6 8 8 6 8 6 6 6 8 8 6
 8 6 6 6 8 8 6 8 6 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8
 8 6 6 8 6 8 6 6 6 8 8 6 8 6 6 6 8 8 6 8 6 6 6 8 8 6 8 6 6 6 8 8 6 8 6 6 6
 8 8 6 8 6 6 6 8 8 6 8 6 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6 8 6
 8 6 8 8 6 6 8 6 8 6 6 6 

In [12]:
for z,r,a in zip(Z,R,atoms):
    print(z,r,a)

6 [4.8925 0.0123 1.2766] C
8 [4.0909 0.2001 0.11  ] O
6 [ 3.0649 -0.68    0.0051] C
8 [ 2.7816 -1.5698  0.7878] O
6 [ 2.2988 -0.372  -1.2221] C
6 [ 3.0079 -0.3254 -2.4348] C
6 [ 2.3403 -0.0775 -3.6323] C
6 [ 0.9638  0.1214 -3.6266] C
6 [ 0.2539  0.0777 -2.4248] C
6 [ 0.9044 -0.1674 -1.1964] C
6 [ 0.0888 -0.1659  0.1014] C
6 [-0.5334  1.1932  0.3679] C
6 [0.2655 2.3168 0.6288] C
6 [-0.3204  3.5674  0.8451] C
6 [-1.7085  3.7148  0.8486] C
7 [-2.2821  4.9883  0.9445] N
6 [-2.4983  2.607   0.5355] C
6 [-1.9193  1.3511  0.3254] C
8 [-2.7909  0.3209  0.0666] O
6 [-2.3067 -0.9649  0.095 ] C
6 [-3.2666 -1.9824  0.0797] C
6 [-2.887  -3.3238  0.1542] C
7 [-3.8432 -4.3385  0.0241] N
6 [-1.5262 -3.634   0.14  ] C
6 [-0.562  -2.6219  0.148 ] C
6 [-0.946  -1.2732  0.1249] C
6 [4.8925 0.0123 1.2766] C
8 [4.0909 0.2001 0.11  ] O
6 [ 3.0649 -0.68    0.0051] C
8 [ 2.7816 -1.5698  0.7878] O
6 [ 2.2988 -0.372  -1.2221] C
6 [ 3.0079 -0.3254 -2.4348] C
6 [ 2.3403 -0.0775 -3.6323] C
6 [ 0.9638  0.1214 -3.626

6 [ 3.8297  4.3446 -0.029 ] C
8 [ 5.0712  4.7912 -0.5952] O
6 [-1.0268  7.3843 -0.5387] C
8 [-0.4503  8.0574  0.5903] O
6 [-2.3485  6.7389 -0.0936] C
8 [-3.3673  7.7557 -0.1529] O
6 [-4.8771  3.0817 -1.4653] C
8 [-3.597   2.6371 -1.9701] O
6 [-5.5524  1.8479 -0.8392] C
8 [-5.5308  0.8055 -1.8209] O
6 [-5.4692 -1.9985  1.6243] C
8 [-6.7421 -1.8489  2.2798] O
6 [-5.3936 -3.3968  1.0066] C
8 [-6.6367 -3.6067  0.313 ] O
6 [-1.3038 -5.5931  1.3643] C
8 [-2.1832 -6.0602  2.3944] O
6 [-0.0554 -4.9436  1.949 ] C
8 [ 0.4988 -5.8057  2.9616] O
6 [ 3.8138 -5.8424  1.7029] C
8 [ 3.1938 -5.0198  2.7137] O
6 [ 5.3112 -5.4915  1.5519] C
8 [ 6.0112 -6.5704  0.9362] O
6 [ 4.0817 -1.0258  2.1588] C
8 [ 2.7024 -1.4169  2.2576] O
6 [4.2012 0.4715 1.8604] C
8 [5.2456 1.0197 2.6847] O
8 [-0.8128  3.5162  1.6132] O
6 [0.0507 2.6933 0.8392] C
6 [1.3922 3.3945 0.5913] C
8 [2.3466 2.3854 0.2378] O
6 [ 3.5671  2.8577 -0.3217] C
8 [4.7049 2.1485 0.1933] O
6 [4.5084 0.739  0.3731] C
6 [ 5.7488 -0.0669 -0.11  ] C
6

8 [5.2456 1.0197 2.6847] O
6 [-7.8771  0.6313  1.1548] C
7 [-6.7791  0.2653  0.264 ] N
6 [-6.9146  0.9098 -1.042 ] C
7 [-5.5314  0.5604  0.8582] N
6 [-4.4572 -0.2986  0.6491] C
8 [-4.4824 -1.3433  0.0115] O
7 [-3.3215  0.1958  1.2684] N
6 [-2.0937 -0.5773  1.2485] C
6 [-1.3688 -0.4659 -0.093 ] C
6 [-0.1061 -1.328  -0.1722] C
6 [ 0.9881 -0.9953  0.8468] C
6 [1.4914 0.4529 0.8313] C
6 [ 2.0554  0.9249 -0.5108] C
7 [ 3.182   0.1362 -0.9656] N
6 [ 4.4353  0.3043 -0.4109] C
8 [4.6871 1.1482 0.4402] O
7 [ 5.335  -0.6113 -0.9482] N
7 [ 6.709  -0.6478 -0.6068] N
6 [ 7.408   0.5955 -0.9364] C
6 [ 6.9211 -1.0237  0.7916] C
6 [-7.8771  0.6313  1.1548] C
7 [-6.7791  0.2653  0.264 ] N
6 [-6.9146  0.9098 -1.042 ] C
7 [-5.5314  0.5604  0.8582] N
6 [-4.4572 -0.2986  0.6491] C
8 [-4.4824 -1.3433  0.0115] O
7 [-3.3215  0.1958  1.2684] N
6 [-2.0937 -0.5773  1.2485] C
6 [-1.3688 -0.4659 -0.093 ] C
6 [-0.1061 -1.328  -0.1722] C
6 [ 0.9881 -0.9953  0.8468] C
6 [1.4914 0.4529 0.8313] C
6 [ 2.0554  0.9249 -0.

In [13]:
# numpy.savez存储多个数组;
# array_dict={'R':R,'N':N,'Z':Z,'id':id_list,'efficiency':efficiency,'smiles':smiles_list}
array_dict={'R':R,'N':N,'Z':Z,'id':id_list,'smiles':smiles_list}
np.savez('3D_canonical_test_lab.npz',**array_dict)

In [14]:
import numpy as np
inhibitor=np.load('3D_canonical_test3.npz',allow_pickle=True)
lst=inhibitor.files
lst

['R', 'N', 'Z', 'id', 'smiles']

In [15]:
for item in lst:
#     np.set_printoptions(threshold=np.inf)
    print(item)
    print(inhibitor[item])
    print(inhibitor[item].shape)

R
[[ 4.8925  0.0123  1.2766]
 [ 4.0909  0.2001  0.11  ]
 [ 3.0649 -0.68    0.0051]
 [ 2.7816 -1.5698  0.7878]
 [ 2.2988 -0.372  -1.2221]
 [ 3.0079 -0.3254 -2.4348]
 [ 2.3403 -0.0775 -3.6323]
 [ 0.9638  0.1214 -3.6266]
 [ 0.2539  0.0777 -2.4248]
 [ 0.9044 -0.1674 -1.1964]
 [ 0.0888 -0.1659  0.1014]
 [-0.5334  1.1932  0.3679]
 [ 0.2655  2.3168  0.6288]
 [-0.3204  3.5674  0.8451]
 [-1.7085  3.7148  0.8486]
 [-2.2821  4.9883  0.9445]
 [-2.4983  2.607   0.5355]
 [-1.9193  1.3511  0.3254]
 [-2.7909  0.3209  0.0666]
 [-2.3067 -0.9649  0.095 ]
 [-3.2666 -1.9824  0.0797]
 [-2.887  -3.3238  0.1542]
 [-3.8432 -4.3385  0.0241]
 [-1.5262 -3.634   0.14  ]
 [-0.562  -2.6219  0.148 ]
 [-0.946  -1.2732  0.1249]
 [ 4.8925  0.0123  1.2766]
 [ 4.0909  0.2001  0.11  ]
 [ 3.0649 -0.68    0.0051]
 [ 2.7816 -1.5698  0.7878]
 [ 2.2988 -0.372  -1.2221]
 [ 3.0079 -0.3254 -2.4348]
 [ 2.3403 -0.0775 -3.6323]
 [ 0.9638  0.1214 -3.6266]
 [ 0.2539  0.0777 -2.4248]
 [ 0.9044 -0.1674 -1.1964]
 [ 0.0888 -0.1659  0.1014]

In [17]:
print(inhibitor["R"][-64:])

[[-2.7850e-01  9.3000e-03  8.2550e-01]
 [-1.5581e+00  1.0700e-02  4.4000e-03]
 [-2.8357e+00 -4.0200e-02  6.4220e-01]
 [-3.0259e+00 -9.4500e-02  2.0394e+00]
 [-4.3056e+00 -1.4200e-01  2.5842e+00]
 [-5.3795e+00 -1.3450e-01  1.7188e+00]
 [-5.2586e+00 -8.3700e-02  3.7660e-01]
 [-4.0109e+00 -3.7800e-02 -1.4260e-01]
 [-3.8839e+00  1.4700e-02 -1.5259e+00]
 [-2.6554e+00  6.4600e-02 -2.1666e+00]
 [-1.4955e+00  6.2500e-02 -1.4004e+00]
 [-5.0194e+00  1.7700e-02 -2.3031e+00]
 [ 2.9100e-02  1.9504e+00  8.0340e-01]
 [-1.3220e+00  1.5571e+00  5.3930e-01]
 [-1.3831e+00  7.0260e-01 -7.3020e-01]
 [-7.3620e-01 -6.1930e-01 -5.7580e-01]
 [-1.6205e+00 -1.7126e+00 -1.2020e-01]
 [-1.3715e+00 -2.1308e+00  1.3328e+00]
 [-2.4633e+00 -2.9181e+00  1.7993e+00]
 [ 6.3160e-01 -8.3440e-01 -8.7800e-01]
 [ 1.3156e+00 -2.3532e+00 -1.0969e+00]
 [ 1.3591e+00  3.5620e-01 -9.5360e-01]
 [ 2.6827e+00  5.6120e-01 -1.3329e+00]
 [ 3.2942e+00  1.7629e+00 -6.5950e-01]
 [ 3.2829e+00 -4.9100e-02 -2.2106e+00]
 [ 2.9100e-02  1.9504e+00

In [18]:
print(sum(N))

4352


In [1]:
from rdkit import Chem

D:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\numpy\.libs\libopenblas.4SP5SUA7CBGXUEOC35YP2ASOICYYEQZZ.gfortran-win_amd64.dll
D:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [4]:
smi = 'NC1SC=C(C2=CC=CC=C2)N=1'
path = 'E:/马金博/缓蚀剂研究/三维数据集制作/test.mol'
contents=[]
f = open(path) # 依次读取文件
content=f.read().split('\n')
#     print(name)
for i in range(4,12+4):
#         print(i)
    a=content[i].split()
    contents.append(a[0:4])
print(contents)

[['4.1719', '0.4287', '0.0880', 'N'], ['2.9931', '-0.1343', '-0.2265', 'C'], ['2.9053', '-1.5350', '-1.2109', 'S'], ['1.1955', '-1.5047', '-1.0819', 'C'], ['0.7967', '-0.4362', '-0.3013', 'C'], ['-0.5925', '-0.1033', '0.0143', 'C'], ['-0.8924', '1.1623', '0.5423', 'C'], ['-2.2070', '1.5189', '0.8550', 'C'], ['-3.2422', '0.6117', '0.6472', 'C'], ['-2.9628', '-0.6513', '0.1307', 'C'], ['-1.6467', '-1.0080', '-0.1826', 'C'], ['1.8432', '0.3490', '0.1682', 'N']]


In [6]:
import numpy as np
R=[]
for content in contents:
    r_float=[]
    for i in content[:3]:
        r_float.append(float(i))
    R.append(r_float)
R=np.array(R)
R

array([[ 4.1719,  0.4287,  0.088 ],
       [ 2.9931, -0.1343, -0.2265],
       [ 2.9053, -1.535 , -1.2109],
       [ 1.1955, -1.5047, -1.0819],
       [ 0.7967, -0.4362, -0.3013],
       [-0.5925, -0.1033,  0.0143],
       [-0.8924,  1.1623,  0.5423],
       [-2.207 ,  1.5189,  0.855 ],
       [-3.2422,  0.6117,  0.6472],
       [-2.9628, -0.6513,  0.1307],
       [-1.6467, -1.008 , -0.1826],
       [ 1.8432,  0.349 ,  0.1682]])